name: Flutter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: flutter test
